services:
  ingress:
    build: ./ingress
    ports:
      - "8000:8000"
    depends_on:
      - redis
    env_file:
      - .env

  analysis:
    build: ./analysis
    depends_on:
      - redis
    env_file:
      - .env

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
