services:
  - type: web
    name: ingress
    runtime: docker
    plan: free
    repo: https://github.com/Tekkieware/decodex-backend
    rootDir: ./ingress
    branch: main
    autoDeploy: true
    envVars:
      - fromGroup: app-env
      - key: REDIS_URL
        fromService:
          type: redis
          name: redis
          property: connectionString
    healthCheckPath: /


  - type: keyvalue
    name: redis
    plan: free
    ipAllowList:
      - source: 0.0.0.0/0
        description: Allow all
    maxmemoryPolicy: noeviction

envVarGroups:
  - name: app-env
    envVars: []
