name: Keep Render Backend Awake

on:
  schedule:
    - cron: "*/15 * * * *" 
  workflow_dispatch:

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Ping backend root
        run: curl -s https://ingress-ajiz.onrender.com/ > /dev/null
